package com.radl.sa.server;

public class ClientProtocol {

	/*
	 * Exists for multiple reasons:
	 * - not to bloat controller
	 * - commands need to be parsed client-side so the client knows what response
	 * to expect from the server
	 * - to have command parsing independent from controller and view
	 * 
	 * Explicitly doesn't reference View.
	 * 
	 * Results are generated by service (consumer gets arraylist)
	 * 
	 * Tells Controller which function to call depending on command. That function
	 * creates a swing worker
	 * 
	 * Whether it comes from a button or from a command, either way i'll have a
	 * function that sends a specific command to the server and then tries to
	 * receive data (eg via a consumer). Decoupling those two steps doesn't make
	 * sense
	 * 
	 * Could have a function that gets a file handle from the view and a function that
	 * takes a file and does the server communication. Then in case i have no gui
	 * i could hand the communcation function a file handle and it still works.
	 * No, doesn't make sense, since the communication function must update the gui
	 * when the SwingWorker finishes. Actually what i just described is just
	 * my client parse service without the server command.
	 * 
	 * Maybe this class should actually just be a switch function that decides
	 * which controller function to call.
	 * 
	 */
}
